- name: Set IPMI IP static
  command: "ipmitool lan set 1 ipsrc static"

- name: Set IPMI IP addr
  command: "ipmitool lan set 1 ipaddr {{ ipmi_ip }} "

- name: Set netmask
  command: "ipmitool lan set 1 netmask {{ipmi_subnet}}"

- name: Set default gateway
  command: "ipmitool lan set 1 defgw ipaddr {{ipmi_gw }}"

- name: Print IPMI ip addr
  command: "ipmitool lan print 1"
  register: result

- debug:
    var: result.stdout

