- hosts: webserver
  become: yes

  tasks:
  - name: Firewalld open only 80 and 22
  # 다른 port 막혀 있고 80 22 만 열려 있는 건 어떻게 확인하지? 
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes    
    loop:
    - http
    - ssh
  
  - name: Reload firewalld
    service:
      name: firewalld
      state: restarted