- hosts: dzgitlab
  become: yes
  tasks:
  - name: Install pip
    yum:
      name: epel-release
      state: present

  - name: Install pip
    yum:
      name: python-pip
      state: present

  - name: Install python3
    yum:
      name: python3
      state: present

  - pip:
      name: pyOpenSSL

  - name: create private key 
    openssl_privatekey:
      path: /home/gitlab/config/gitlab.dz.io.key

  - name: Generate an OpenSSL Certificate Signing Request
    openssl_csr:
      path: /home/gitlab/config/gitlab.dz.io.csr
      privatekey_path: /home/gitlab/config/gitlab.dz.io.key
      common_name: gitlab.dz.io

# error using python2 instead of python3
  - name: Generate a Self Signed OpenSSL certificate
    openssl_certificate:
      path: /home/gitlab/config/gitlab.dz.io.crt
      privatekey_path: /home/gitlab/config/gitlab.dz.io.key
      csr_path: /home/gitlab/config/gitlab.dz.io.csr
      provider: selfsigned
      entrust_not_after: "+3650d"
