- hosts: ubun1804
  become: yes
  vars_files:
    - /etc/ansible/vars/user.yml
  tasks:  
  - name: Create user
    user:
      name: "{{ item }}"
      state: present  
    with_items:
      - "{{ students[0] }}"
    