# - hosts: adzdias
- hosts: armyw1
  become: yes
  # user: diamanti
  tasks:
  # - name: tag & push an image
  #   docker_image:
  #     name: docker.io/erdia22/tomcat-mailbox
  #     repository: gitlab.dz-ebp.io:5050/jerry/bizcubex/tomcat-mailbox
  #     tag: 1.4
  #     push: yes
  #     source: local
  - name: Log into private registry and force re-authorization
    docker_login:
      registry: gitlab.dz-army.io:5050/jerry/dz-army
      username: jerry
      password: Diamanti1! 

  - name: pull an image
    docker_image:
      name: docker.io/bitnami/{{item}}
      source: pull
    loop:
    - redis-sentinel:6.0.8-debian-10-r55
    - redis:6.0.9-debian-10-r0

  - name: tag & push an image
    docker_image:
      name: docker.io/bitnami/{{item}}
      repository: gitlab.dz-army.io:5050/jerry/dz-army/{{item}}
      tag: latest
      push: yes
      source: local
    loop:
    - redis-sentinel:6.0.8-debian-10-r55
    - redis:6.0.9-debian-10-r0
    # - human
    # - financial
    # - crm
    # - messenger
    # - event
    # - eap
    # - gw
    # - mail
    # - fax
    # - board
    # - apiproxy
    # - proxymgw
    # - webauthn
    # - ladder
    # - kiss
    # - mailbox
    # - usagestatisticchartui
    # - sms
    # - personal
    # - logis
    # - ea
    # - proxypush
    # - keep
    # - ecm-convert


