- hosts: dias
  become: yes
  gather_facts: no
  tasks:
  - name: copy rules to remote
    copy:
      src: /home/spkr/12.Privatek8sCode/29.Prometheus/prometheus.yml
      dest: /etc/diamanti/prometheus/prometheus.yml
      backup: yes
      # owner: dba
      # group: dba
