- hosts: dzarmys
  become: yes
  gather_facts: no
  tasks:
  - name: mkdir
    file:
      path: /etc/docker/certs.d/gitlab.dz-army.io:5050
      state: directory

  - name: copy certs to remote
    copy:
      src: /home/spkr/gitlab.dz-army.io.crt
      dest: /etc/docker/certs.d/gitlab.dz-army.io:5050/gitlab.spkr.io.crt
      backup: yes
      # owner: dba
      # group: dba
