- hosts: dias
  become: yes
  gather_facts: no
  tasks:
  - name: copy rules to remote
    copy:
      src: /home/spkr/02.k8s/diamanti-k8s-bootcamp/29.Prometheus/alert.rules
      dest: /etc/diamanti/prometheus/alert.rules
      backup: yes
      # owner: dba
      # group: dba
