# - hosts: adzdias
- hosts: localhost
  # become: yes
  # user: diamanti
  tasks:
  - name: pull an image
    docker_image:
      name: "{{ item }}"
      source: pull
    loop:
    - nkkim/mariadb-ssh:10.2.13

  # - name: pull an image
  #   community.general.docker_image:
  #     name: pacur/centos-7
  #     source: pull
