- hosts: localhost
  become: yes
  tasks:
  - name: Build an image and push it to a private repo
    community.general.docker_image:
      build:
        path: /mnt/c/Users/erdia/Documents/07.Customers/01.Douzone
        dockerfile: "{{ item.file }}"
      name: "{{ item.name }}"
      tag: 1.0
      # push: yes
      source: build
    loop:
    - { file: 'tomcat-apiproxy.dockerfile', name: 'erdia22/tomcat-apiproxy'}
    - { file: 'tomcat-board.dockerfile', name: 'erdia22/tomcat-board'}