- hosts: localhost
  become: yes
  tasks:
  - name: Build an image and push it to a private repo
    community.general.docker_image:
      build:
        # path: /mnt/c/Users/erdia/Documents/07.Customers/01.Douzone
        path: /mnt/c/Users/erdia/Documents/07.Customers
        # dockerfile: tomcat-apiproxy.dockerfile
      name: erdia22/tomcat-apiproxy
      tag: 1.0
      # push: yes
      source: build
