- hosts: localhost
  # become: yes
  tasks:
  - name: Build an image and push it to a private repo
    docker_image:
      build:
        path: /mnt/c/Users/erdia/Documents/07.Customers/01.Douzone/02.dockerfile
        dockerfile: "{{ item.file }}"
      name: "{{ item.name }}"
      tag: 1.4
      # push: yes
      source: build
    loop:
    - { file: 'tomcat-board.dockerfile', name: 'erdia22/tomcat-board'}
    - { file: 'tomcat-crm.dockerfile', name: 'erdia22/tomcat-crm'}
