- hosts: cent8
  become: yes

  tasks:
  - name: add firewall rule for http and ssh
  # 다른 port 막혀 있고 80 22 만 열려 있는 건 어떻게 확인하지? 
    firewalld:
      zone: public
      service: "{{ item }}"
      state: enabled
      permanent: yes   
      immediate: yes
    loop:
    - http
    - https
    - ssh

  - name: add firewall rule for 8080 - 8084
  # 다른 port 막혀 있고 80 22 만 열려 있는 건 어떻게 확인하지? 
    firewalld:
      zone: public
      port: 8080-8084/tcp
      state: enabled
      permanent: yes   
      immediate: yes

  - name: add firewall rule rich rule 443 to 8443
    firewalld:
      rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=843
      state: disabled
      permanent: yes
      immediate: yes