- hosts: rkes
  become: yes
  tasks:
    - name: Change hostname from inventory hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Cat hostname
      command: hostname
      register: result
    
    - debug:
        var: result.stdout