- hosts: cent8
  become: yes

  tasks:
    - name: replace line with replace module
      lineinfile:
        path:  /var/www/html/index.html
        regexp: "^added"    # added로 시작하는 line 변경 
        line: "line replaced by lineinfile module"    # line 전체를 변경한다.
