- hosts: cent8
  become: yes
  tasks:
  - name: Start and enable the httpd service
    service:
      name: httpd
      state: started
      enabled: yes
  
  - name: start and enable the firewalld service
    service:
      name: firewalld
      state: started
      enabled: yes
  