- hosts: dzdias
  become: yes
  tasks:
  - name: Start and enable the httpd service
    service:
      name: {{ item }}
      state: started
      enabled: yes
    loop:
    - armada
    - dock 
    - bosun
  # - name: start and enable the firewalld service
  #   service:
  #     name: firewalld
  #     state: started
  #     enabled: yes
  