- hosts: cent8
  become: yes

  tasks:
    - name: Test template module
      template:
        src: /home/spkr/01.Ansible/06.template/testFile.j2
        dest: /tmp/ansible-template-test.txt
        owner: spkr
        group: spkr
        mode: 0644    # 644 하면 안되고 0644 해야 한다.
        