---
# This is the software installation plyabook

- name: Create users
  hosts: cent8
  become: yes

  tasks:
  - group:
      name: web
      state: present

  - user:
      name: "{{ item }}"
      groups: web
      append: yes
      state: present
    loop:
    - devs
    - security
    - admins    