- hosts: dzdias
  become: yes
  tasks:
  - name: Change password
    user:
      name: diamanti
      # diamanti password
      password: $6$oYA2Qnnx0M$6PmYawfvUjTBW9nwYjRvFDUacfBne7zcy4JKgBKc8JyaoZ2Njth9ahry9a.NOisQeoCJcxVJ9x4wiuviVAe7a/
