- hosts: webserver
  become: yes
# 개별 firewall rule 삭제는 안되고
# firewalld 삭제 후 재설치

# 삭제 후 재설치해도 Rule이 그대로 있네.
# loop 하면 될 듯
  tasks:
  - name: Remove firewall pkg
    yum:
      name: firewall
      state: absent
  
  # firewall 은 pkg 이름도 firewalld 이구나
  - name: Install firewall pkg
    yum:
      name: firewalld
      state: present 
  
  - name: Serivce started and enabled
    service:
      name: firewalld
      state: started
      enabled: yes

  # - name: Remove all service & ports rules
  # # 다른 port 막혀 있고 80 22 만 열려 있는 건 어떻게 확인하지? 
  #   firewalld:
  #     service: all
  #     # port: all/tcp
  #     state: absent
  #     permanent: yes    
  
  # - name: Reload firewalld
  #   service:
  #     name: firewalld
  #     state: restarted