- hosts: gitlab
  become: yes
  tasks:
  - name: Install epel-release
    yum:
      name: epel-release
      state: present

  - name: Install python-pip
    yum:
      name: python-pip
      state: present

  - pip:
      name: docker
