- command: "ipmitool lan set 3 ipsrc static"
- command: "ipmitool lan set 3 netmask 255.255.240.0"
- command: "ipmitool lan set 3 defgw ipaddr 172.17.17.2"
- command: "ipmitool lan set 3 ipaddr {{ipmi_ip}} "
- command: "ipmitool lan print 3"
  register: result

- debug:
    var: result.stdout

