- hosts: drone
  become: yes

  tasks:
  - name: allow firewall rule for nfs and nfs3
  # 다른 port 막혀 있고 80 22 만 열려 있는 건 어떻게 확인하지? 
    firewalld:
      service: "{{ item }}"
      state: enabled
      permanent: yes   
      immediate: yes
    loop:
    - nfs
    - nfs3
